# Generated by Django 4.0.5 on 2022-06-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(to='ecommerceApp.shop'),
        ),
    ]
