# Generated by Django 4.0.5 on 2022-07-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_alter_product_category_alter_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(related_name='shop_name', to='ecommerceApp.shop'),
        ),
    ]
